block.settings.example_configurable_text:
  type: block_settings
  label: 'Example configurable text block configuration'
  mapping:
    instagram_d8_string:
      type: text
      label: 'Block contents'
